export const Message = {
  BAD_REQUEST: "데이터 형식이 올바르지 않습니다.",
  COOKIE_ERROR_OCCURRED: "전달된 쿠키에서 오류가 발생하였습니다.",

  NICKNAME_FORMAT_MISMATCH: "닉네임의 형식이 일치하지 않습니다.",
  PASSWORD_FORMAT_MISMATCH: "패스워드 형식이 일치하지 않습니다.",
  PASSWORD_INCLUDED_NICKNAM: "패스워드에 닉네임이 포함되어 있습니다.",

  SIGNUP_FAILED: "회원 가입에 실패하였습니다.",
  SIGNUP_SUCCEED: "회원 가입에 성공하였습니다.",

  DUPLICATE_NICKNAME: "중복된 닉네임입니다.",
  USER_DOES_NOT_EXIST: "닉네임 또는 패스워드를 확인해주세요.",

  LOGIN_FAILED: "로그인에 실패하였습니다.",
  LOGIN_SUCCEED: "로그인에 성공하였습니다.",
  LOGIN_REQUIRED: "로그인이 필요한 기능입니다.",

  POST_CREATED: "게시글 작성에 성공하였습니다.",
  POST_NOT_FOUND: "게시글 조회에 실패했습니다.",
  POST_NOT_CREATED: "게시글 작성에 실패하였습니다.",
  POST_DOES_NOT_EXIST: "게시글이 존재하지 않습니다.",
  POST_TITLE_FORMAT_MISMATCH: "게시글 제목의 형식이 일치하지 않습니다.",
  POST_CONTETN_FORMAT_MISMATCH: "게시글 내용의 형식이 일치하지 않습니다.",
  POST_EDIT_PERMISSION_DENIED: "게시글 수정 권한이 존재하지 않습니다.",
  POST_DELETE_PERMISSION_DENIED: "게시글 삭제 권한이 존재하지 않습니다.",
  POST_DELETION_NOT_COMPLETED: "게시글 삭제가 정상적으로 처리되지 않았습니다.",
  POST_DELETION_FAILED: "게시글 삭제에 실패하였습니다.",
  POST_EDIT_NOT_COMPLETED: "게시글 수정이 정상적으로 처리되지 않았습니다.",
  POST_EDIT_FAILED: "게시글 수정에 실패하였습니다.",
  POST_EDIT_SUCCESS: "게시글을 수정하였습니다.",
  POST_DELETE_SUCCESS: "게시글을 삭제하였습니다.",

  COMMENT_EMPTY: "댓글 내용을 입력해주세요.",
  COMMENT_CREATED: "댓글 작성에 성공하였습니다.",
  COMMENT_NOT_FOUND: "댓글 조회에 실패했습니다.",
  COMMENT_NOT_CREATED: "댓글 작성에 실패하였습니다.",
  COMMENT_DOES_NOT_EXIST: "댓글이 존재하지 않습니다.",
  COMMENT_TITLE_FORMAT_MISMATCH: "댓글 제목의 형식이 일치하지 않습니다.",
  COMMENT_COMMENT_FORMAT_MISMATCH: "댓글 내용의 형식이 일치하지 않습니다.",
  COMMENT_EDIT_PERMISSION_DENIED: "댓글 수정 권한이 존재하지 않습니다.",
  COMMENT_DELETE_PERMISSION_DENIED: "댓글 삭제 권한이 존재하지 않습니다.",
  COMMENT_DELETION_NOT_COMPLETED: "댓글 삭제가 정상적으로 처리되지 않았습니다.",
  COMMENT_DELETION_FAILED: "댓글 삭제에 실패하였습니다.",
  COMMENT_EDIT_NOT_COMPLETED: "댓글 수정이 정상적으로 처리되지 않았습니다.",
  COMMENT_EDIT_FAILED: "댓글 수정에 실패하였습니다.",
  COMMENT_EDIT_SUCCESS: "댓글을 수정하였습니다.",
  COMMENT_DELETE_SUCCESS: "댓글을 삭제하였습니다.",

  INTERNAL_SERVER_ERROR: "서버 내부 오류가 발생했습니다.",
  DATABASE_ERROR: "데이터베이스 오류가 발생했습니다.",
  UNEXPECTED_ERROR: "예상치 못한 오류가 발생했습니다.",

  POST_LIKE: "게시글의 좋아요를 등록하였습니다.",
  POST_UNLIKE: "게시글의 좋아요를 취소하였습니다.",
};
